---
- name: Configure davfs2 locks
  lineinfile: path=/etc/davfs2/davfs2.conf regexp="^#use_locks" line="use_locks 0"

- name: Allow to user run mount command
  file:
    path: "{{ item }}"
    mode: '4755'
  loop:
    - /usr/sbin/mount.davfs
    - /usr/sbin/umount.davfs

- name: Add cridentials
  lineinfile:
    path: /etc/davfs2/secrets
    line: "{{ item.src }} {{ item.login }} {{ item.password }}"
    state: present
  no_log: true
  with_items: "{{ davfs2_mounts }}"

- name: Add mount path into fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ item.src }}\t{{ item.mount_path }}\tdavfs\tnoauto,_netdev,rw,user\t0\t0"
    state: present
  no_log: true
  with_items: "{{ davfs2_mounts }}"