---
- name: Create mount path
  file:
    path: "{{ item.mount_path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  no_log: true
  with_items: "{{ davfs2_mounts }}"
